---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: true
  hosts: test-kitchen
  ansible_verbose: true
  ansible_verbosity: 1
  ansible_diff: true
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>

verifier:
  ruby_bindir: '/usr/bin'

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
